# 서버 포트 설정
server.port=8080

# 서비스 이름 설정
spring.application.name=gateway-service

# [CORS 설정] 리액트(3000) 요청 허용
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

# [라우팅 설정 1] RF 분석 모듈 (8084 포트)
spring.cloud.gateway.routes[0].id=rf-analysis-route
spring.cloud.gateway.routes[0].uri=http://localhost:8084
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/analysis/**

# [라우팅 설정 2] 만약 다른 호스트/포트의 모듈이 있다면 (예: 8081 포트)
# spring.cloud.gateway.routes[1].id=other-service-route
# spring.cloud.gateway.routes[1].uri=http://localhost:8081
# spring.cloud.gateway.routes[1].predicates[0]=Path=/api/other/**
AUTH_SERVICE_PORT=8081