spring.application.name=common-module
# 1. Oracle Database ?? ?? (???? ??, ?? ? ??? ??)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME:ml_admin}
spring.datasource.password=${DB_PASSWORD:ml_password123}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# 2. JPA/Hibernate ??
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
# ??? ?? ? ??? ?? ?? ???? (?? ???? ??)
spring.jpa.hibernate.ddl-auto=update

# 3. ?? ?? ?? (?? ???)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

# 4. (????) ?? ?? ? ?? ???
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true