server.port=${GATEWAY_PORT}
spring.application.name=gateway-service

spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOriginPatterns=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].maxAge=3600

spring.cloud.gateway.routes[0].id=authservice
spring.cloud.gateway.routes[0].uri=http://authservice:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=communityservice
spring.cloud.gateway.routes[1].uri=http://communityservice:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/community/**

spring.cloud.gateway.routes[2].id=lstmanalysis
spring.cloud.gateway.routes[2].uri=http://lstmanalysis:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/analysis/lstm/**

spring.cloud.gateway.routes[3].id=rfanalysis
spring.cloud.gateway.routes[3].uri=http://rfanalysis:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/analysis/rf/**

spring.cloud.gateway.routes[4].id=mlservice
spring.cloud.gateway.routes[4].uri=http://mlservice:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/ml/**

spring.cloud.gateway.routes[5].id=paymentservice
spring.cloud.gateway.routes[5].uri=http://paymentservice:8086
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/payment/**
